/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package multi_threads;

import main.java.multi_threads.race_condition.RaceCondition;

public class App {

  public static void main(String[] args) {
    RaceCondition raceCondition = new RaceCondition();
    raceCondition.startTwoThreads();
    System.out.println(raceCondition.getShardRecource());
  }
}
