/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package multi_threads;

import multi_threads.explict_lock.ExplictLock;

public class App {

  public static void main(String[] args) {
    ExplictLock test = new ExplictLock();
    test.startThread();
  }
}
