/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package multi_threads;

import org.junit.jupiter.api.Test;

class AppTest {

  @Test
  void appHasAGreeting() {
    App classUnderTest = new App();
  }
}
